import SpotifyWrapper from 'spotify-wrapper';

const spotify = new SpotifyWrapper({
  token: 'BQA3rUujTWdduv92ovpdeeT75HQByYu_YulhFV1O3QvPU9ipCQyDs91YLvBFRBqc55iv5Gb0WcLW5tLFguotPSRE8E6wqyu1zWcT4i7mmMH0AnJopbCx-3rE1MhZvfLuc1LBqKPFQIaPnpPeL1kOpGJCbMbavLJRFaZ5Qdrg46TMEFiLwcrT7STGStTghrhMhtwAUP0ApBkFWwfgBlXtKeFw1RLc8hsydUyyJpbRLd_L5cRJnxTJQUsXpcObr1ltBW6HsbjrFf5gmw'
})

export default spotify;
